<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function omnipedia_user_help(
  string $routeName, RouteMatchInterface $routeMatch
) {

  switch ($routeName) {
    case 'user.login':
    case 'user.pass':

      /** @var \Drupal\omnipedia_commerce\Service\ContentAccessProductInterface */
      $contentAccessProduct = \Drupal::service(
        'omnipedia_commerce.content_access_product'
      );

      /** @var \Drupal\Core\Session\AccountProxyInterface */
      $currentUser = \Drupal::service('current_user');

      /** @var \Drupal\commerce_product\Entity\ProductInterface|null */
      $product = $contentAccessProduct->getBaseProduct();

      // Don't render anything if the base product has not been configured.
      if (
        !\is_object($product) ||
        !$product->access('view', $currentUser)
      ) {
        return '';
      }

      /** @var \Drupal\Core\Utility\LinkGeneratorInterface The Drupal link generator service. */
      $linkGenerator = \Drupal::service('link_generator');

      return '<p>'. \t(
        'Don\'t have an account? You can acquire one by @joining.',
        ['@joining' => $linkGenerator->generate(
          \t('joining Omnipedia'),
          $product->toUrl()
        )]
      ) . '</p>';

  }

}

/**
 * Implements \hook_page_attachments_alter().
 *
 * The EU Cookie Compliance module introduced a change (very likely in 8.x-1.15)
 * that forces the banner markup to be attached even on admin pages when the
 * option to exclude admin pages is enabled. This hook removes the
 * eu_cookie_compliance libraries and drupalSettings key if the setting to
 * exclude admin pages is set to true. This is a hack and intended as a
 * temporary workaround.
 *
 * Note that the 'config:eu_cookie_compliance.settings' cache tag is not removed
 * as that should be present even if the pop-up isn't present, so that it may be
 * added when that config changes depending on settings.
 *
 * @see \hook_eu_cookie_compliance_show_popup_alter()
 *   Use of this hook was attempted but the module seems to override whatever we
 *   set after that's invoked.
 *
 * @see https://www.drupal.org/project/eu_cookie_compliance/issues/3236590
 *
 * @see https://www.drupal.org/project/eu_cookie_compliance/releases/8.x-1.15
 *
 * @todo Remove this once we switch to another cookie/privacy pop-up.
 */
function omnipedia_user_page_attachments_alter(array &$variables): void {

  /** @var \Drupal\Core\Routing\AdminContext The Drupal admin context service. */
  $adminContext = \Drupal::service('router.admin_context');

  if (
    $adminContext->isAdminRoute() &&
    isset($variables['#attached']['drupalSettings']['eu_cookie_compliance'])
  ) {

    /** @var \Drupal\Core\Config\ImmutableConfig The EU Cookie Compliance module config. */
    $config = \Drupal::config('eu_cookie_compliance.settings');

    if ($config->get('exclude_admin_theme') === false) {
      return;
    }

    unset($variables['#attached']['drupalSettings']['eu_cookie_compliance']);

    foreach ($variables['#attached']['library'] as $key => $value) {
      if (\strpos($value, 'eu_cookie_compliance/') === 0) {
        unset($variables['#attached']['library'][$key]);
      }
    }

  }

}
